version: '3'

services:
  xray:
    env_file:
      - .env
    build:
      context: build
      dockerfile: xray
      args:
        RELEASE: ${RELEASE:-1.8.4}
    volumes:
      - ./config.json:/xray/config.json
    ports:
      - "443:443"

  dns:
    build:
      context: build
      dockerfile: dns
    volumes:
      - ./dnsmask.conf:/etc/dnsmask.conf
